# H1 TITLE
## H2 TITLE

In [1]:
print("Buy the dip ?")

Buy the dip ?


In [3]:
import numpy as np
arr = np.array([
    10,
    3.14,
    "hello",
    {"a": 1},
    [1, 2],
    (1, 2),
    {1, 2},
    True
], dtype=object)
for i in arr:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [4]:
arr = np.zeros(300)

In [5]:
arr = np.arange(1, 101)

In [6]:
odd = arr[::2]

In [8]:
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [9]:
even_reversed = arr[::-2]

In [10]:
print(even_reversed)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [11]:
arr[1::3] = 0

In [12]:
print(arr)

[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


In [9]:
np.random.seed(888)
np.random.randn(100) #kaya3ti ar9am 9rab mn zero 
np.random.randint(1,11,(8,8))
np.random.randint(1,18,(4,2,5))

array([[[ 5,  2, 13, 16, 15],
        [ 5,  5,  2, 11,  3]],

       [[ 8, 13,  6,  4, 17],
        [ 2,  8,  1, 13, 10]],

       [[12, 17, 17, 12,  1],
        [10,  8, 17,  5, 11]],

       [[ 9, 14,  2, 15, 13],
        [12, 14,  6, 14,  2]]])

In [11]:
x=np.arange(1,51)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
y=np.arange(51,101)
y

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
z=np.concatenate((x,y))
z

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
z=z.reshape(10,10)
z

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
cl=np.ones((9,9),dtype=np.int8) # range kaykon sghir dyl int8 okaydi memory 9al
cl

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [33]:
cl[1:-1,1:-1]=0
cl[2:-2,2:-2]=1
cl[3:-3,3:-3]=0
cl[4:-4,4:-4]=1
cl

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [37]:
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)

In [44]:
res = array_1[:, np.newaxis] * array_2 # chenage to col or col to row array_1.flatten()
res

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15]], dtype=int8)

In [5]:
import numpy as np

#kaycreate random generator. 123 hiya seed bach nafs code y3ti nafs random data.
generator = np.random.default_rng(123) 
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
print(grades)

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]


In [6]:
#grades[ rows , columns ] grades[:, 1] get all rows and col number 1
col3=np.where(np.isnan(grades[:,0]),grades[:, 1],grades[:, 0])
col3

array([7., 2., 8., 9., 8., 2., 8., 6., 9., 8.])

In [7]:
grades=np.column_stack((grades,col3)) #vstack for added row
grades

array([[ 7.,  1.,  7.],
       [nan,  2.,  2.],
       [nan,  8.,  8.],
       [ 9.,  3.,  9.],
       [ 8.,  9.,  8.],
       [nan,  2.,  2.],
       [ 8.,  2.,  8.],
       [nan,  6.,  6.],
       [ 9.,  2.,  9.],
       [ 8.,  5.,  8.]])

In [9]:
#EX8
data=np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1,dtype=np.float32)
data.nbytes

76752

In [10]:
rows=data[[1,6,11]]
rows

array([[7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.900e+00, 6.000e-01, 6.000e-02, 1.600e+00, 6.900e-02, 1.500e+01,
        5.900e+01, 9.964e-01, 3.300e+00, 4.600e-01, 9.400e+00, 5.000e+00],
       [7.500e+00, 5.000e-01, 3.600e-01, 6.100e+00, 7.100e-02, 1.700e+01,
        1.020e+02, 9.978e-01, 3.350e+00, 8.000e-01, 1.050e+01, 5.000e+00]],
      dtype=float32)

In [11]:
np.isnan(rows).any()
# ~x kadir l3aks dyl dakchi li3andk 

np.False_

In [6]:
rows = rows[~np.isnan(rows).any(axis=1)] # Keep only rows that do NOT contain any NaN values
rows

array([[7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.900e+00, 6.000e-01, 6.000e-02, 1.600e+00, 6.900e-02, 1.500e+01,
        5.900e+01, 9.964e-01, 3.300e+00, 4.600e-01, 9.400e+00, 5.000e+00],
       [7.500e+00, 5.000e-01, 3.600e-01, 6.100e+00, 7.100e-02, 1.700e+01,
        1.020e+02, 9.978e-01, 3.350e+00, 8.000e-01, 1.050e+01, 5.000e+00]],
      dtype=float32)

In [8]:
(data[:,10]>20).any()

np.False_

In [14]:
#np.average(data[:,10]) # far9 bin mean o average ila kan 3andk weights ya3ni mo3amilat 
np.nanmean(data[:, 10])

np.float32(10.422984)

In [15]:
ph=data[:,8]
np.min(ph)

np.float32(2.74)

In [16]:
np.max(ph)

np.float32(4.01)

In [17]:
np.mean(ph)

np.float32(3.3111134)

In [18]:
np.percentile(ph, 25)

np.float32(3.21)

In [19]:
np.percentile(ph, 50)

np.float32(3.31)

In [20]:
np.percentile(ph, 75)

np.float32(3.4)

In [21]:
np.percentile(ph, [25, 50, 75]) #position = (percentage / 100) × (number_of_values - 1)

array([3.21000004, 3.30999994, 3.4000001 ])

In [28]:
s20=np.percentile(data[:,9],20)

In [38]:
sulphates=data[:, 9] < s20
sulphates

array([False, False, False, ..., False, False, False], shape=(1599,))

In [37]:
quality = data[sulphates,11] #mask automatique get colomumns only have row true 
quality

array([5., 7., 5., 4., 6., 5., 6., 4., 4., 5., 5., 5., 5., 5., 5., 4., 5.,
       5., 4., 5., 5., 5., 6., 5., 5., 5., 5., 5., 5., 6., 5., 5., 5., 5.,
       4., 4., 5., 5., 5., 5., 5., 4., 5., 5., 5., 6., 5., 6., 5., 5., 6.,
       5., 5., 5., 5., 6., 5., 5., 5., 5., 5., 6., 5., 5., 5., 6., 5., 5.,
       5., 5., 5., 6., 4., 6., 5., 5., 5., 6., 5., 6., 4., 5., 6., 6., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 6., 5., 5., 5., 5., 6., 5., 5., 5., 5., 5., 5.,
       6., 5., 6., 6., 5., 5., 5., 5., 6., 5., 6., 6., 5., 5., 5., 5., 5.,
       6., 6., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 7., 7., 5., 5., 5.,
       6., 5., 6., 3., 6., 6., 7., 5., 5., 5., 5., 7., 5., 5., 6., 5., 5.,
       6., 5., 5., 6., 6., 5., 6., 6., 6., 6., 5., 5., 6., 7., 6., 7., 5.,
       6., 5., 6., 5., 5., 5., 6., 6., 5., 7., 6., 5., 5., 4., 5., 6., 5.,
       6., 4., 5., 5., 6., 6., 5., 5., 4., 6., 6., 4., 5., 5., 5., 5., 4.,
       5., 5., 6., 5., 4.

In [34]:
np.nanmean(quality)

np.float32(5.1854305)

In [42]:
maxQl = np.nanmax(data[:, 11])
maxQl

np.float32(8.0)

In [49]:
best = data[:,11]==maxQl

In [47]:
bestwine=data[best]
bestwine

array([[7.9000e+00, 3.5000e-01, 4.6000e-01, 3.6000e+00, 7.8000e-02,
        1.5000e+01, 3.7000e+01, 9.9730e-01, 3.3500e+00, 8.6000e-01,
        1.2800e+01, 8.0000e+00],
       [1.0300e+01, 3.2000e-01, 4.5000e-01, 6.4000e+00, 7.3000e-02,
        5.0000e+00, 1.3000e+01, 9.9760e-01, 3.2300e+00, 8.2000e-01,
        1.2600e+01, 8.0000e+00],
       [5.6000e+00, 8.5000e-01, 5.0000e-02, 1.4000e+00, 4.5000e-02,
        1.2000e+01, 8.8000e+01, 9.9240e-01, 3.5600e+00, 8.2000e-01,
        1.2900e+01, 8.0000e+00],
       [1.2600e+01, 3.1000e-01, 7.2000e-01, 2.2000e+00, 7.2000e-02,
        6.0000e+00, 2.9000e+01, 9.9870e-01, 2.8800e+00, 8.2000e-01,
        9.8000e+00, 8.0000e+00],
       [1.1300e+01, 6.2000e-01, 6.7000e-01, 5.2000e+00, 8.6000e-02,
        6.0000e+00, 1.9000e+01, 9.9880e-01, 3.2200e+00, 6.9000e-01,
        1.3400e+01, 8.0000e+00],
       [9.4000e+00, 3.0000e-01, 5.6000e-01, 2.8000e+00, 8.0000e-02,
        6.0000e+00, 1.7000e+01, 9.9640e-01, 3.1500e+00, 9.2000e-01,
        1.1700e+01,

In [43]:
minQl = np.nanmin(data[:, 11])
minQl

np.float32(3.0)

In [50]:
worst=data[:,11]==minQl

In [52]:
worstWine=data[worst]
worstWine

array([[1.1600e+01, 5.8000e-01, 6.6000e-01, 2.2000e+00, 7.4000e-02,
        1.0000e+01, 4.7000e+01, 1.0008e+00, 3.2500e+00, 5.7000e-01,
        9.0000e+00, 3.0000e+00],
       [1.0400e+01, 6.1000e-01, 4.9000e-01, 2.1000e+00, 2.0000e-01,
        5.0000e+00, 1.6000e+01, 9.9940e-01, 3.1600e+00, 6.3000e-01,
        8.4000e+00, 3.0000e+00],
       [7.4000e+00, 1.1850e+00, 0.0000e+00, 4.2500e+00, 9.7000e-02,
        5.0000e+00, 1.4000e+01, 9.9660e-01, 3.6300e+00, 5.4000e-01,
        1.0700e+01, 3.0000e+00],
       [1.0400e+01, 4.4000e-01, 4.2000e-01, 1.5000e+00, 1.4500e-01,
        3.4000e+01, 4.8000e+01, 9.9832e-01, 3.3800e+00, 8.6000e-01,
        9.9000e+00, 3.0000e+00],
       [8.3000e+00, 1.0200e+00, 2.0000e-02, 3.4000e+00, 8.4000e-02,
        6.0000e+00, 1.1000e+01, 9.9892e-01, 3.4800e+00, 4.9000e-01,
        1.1000e+01, 3.0000e+00],
       [7.6000e+00, 1.5800e+00, 0.0000e+00, 2.1000e+00, 1.3700e-01,
        5.0000e+00, 9.0000e+00, 9.9476e-01, 3.5000e+00, 4.0000e-01,
        1.0900e+01,