In [1]:
import numpy as np

In [10]:
x2=np.array([[1,5,np.nan],[8,7,4]])
x2

array([[ 1.,  5., nan],
       [ 8.,  7.,  4.]])

In [3]:
x2[:,0]

array([1, 8])

In [4]:
x2[0]

array([1, 5, 3])

In [17]:
np.isnan(x2).any()

np.True_

##  Copying Arrays 

In [20]:
arr=np.array([[1,5,4,8],[8,7,4,8],[8,1,4,9]])
arr

array([[1, 5, 4, 8],
       [8, 7, 4, 8],
       [8, 1, 4, 9]])

In [23]:
sub_arr=arr[:2,:2]
sub_arr

array([[1, 5],
       [8, 7]])

In [24]:
sub_arr[1,1]=0
sub_arr

array([[1, 5],
       [8, 0]])

In [25]:
arr

array([[1, 5, 4, 8],
       [8, 0, 4, 8],
       [8, 1, 4, 9]])

In [26]:
arr_copy=sub_arr.copy()
arr_copy

array([[1, 5],
       [8, 0]])

In [27]:
arr_copy[0,0]=0
arr_copy

array([[0, 5],
       [8, 0]])

In [28]:
sub_arr

array([[1, 5],
       [8, 0]])

## Reshape Arrays

In [31]:
r1=np.arange(1,10)
r1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
r2=r1.reshape(3,3)
r2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
r3=np.arange(10).reshape(2,5) #.shape bach tchof format 
r3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
r1.reshape(-1,1).shape

(9, 1)

In [46]:
r4=np.array([1,4,5])
r4

array([1, 4, 5])

In [50]:
r4.shape

(3,)

In [52]:
r4.reshape((3,1))

array([[1],
       [4],
       [5]])

In [53]:
r4.shape

(3,)

In [56]:
r4.ndim

1

In [58]:
r4[np.newaxis,:].shape

(1, 3)

In [59]:
r4[:,np.newaxis].shape

(3, 1)

In [74]:
grid=np.array(([2,3,4,5,6,4],[5,2,2,4,1,0]))
grid

array([[2, 3, 4, 5, 6, 4],
       [5, 2, 2, 4, 1, 0]])

In [77]:
grid.reshape(4,-1) #-1 kaat3ni ykmlik tartib 3la 7sab ch7al b9a man col wala row 

array([[2, 3, 4],
       [5, 6, 4],
       [5, 2, 2],
       [4, 1, 0]])

## Concatenate Arrays

In [81]:
c1=np.array([1,2,3])
c2=np.array([6,5,4])
np.concatenate([c1,c2])

array([1, 2, 3, 6, 5, 4])

In [4]:
x=np.full((2,3),1)
y=np.full((2,3),9)
print(x)
print()
print(y)

[[1 1 1]
 [1 1 1]]

[[9 9 9]
 [9 9 9]]


In [5]:
np.concatenate((x,y),axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [6]:
np.concatenate((x,y),axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [42]:
z=np.array([1,2,3])
z2=np.array([[1,2,3],[4,5,6]])
print(z)
print()
print(z2)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [28]:
np.vstack([z,z2])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [36]:
z=z.reshape(1,3)
z

array([[1, 2, 3]])

In [38]:
z2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate((z,z2),axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
z=np.array([[1,2]]).reshape(-1,1)
z.shape

(2, 1)

In [59]:
z2

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.hstack([z2,z])

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

## Split Arrays

In [63]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
s1,s2,s3=np.split(s,[3,6])
print(s1,s2,s3)

[0 1 2] [3 4 5] [6 7 8 9]


In [67]:
grid=np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
up,low=np.vsplit(grid,[2])
print(up)
print()
print(low)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [70]:
left,right=np.hsplit(grid,[2])
print(left)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Ufuncs

In [79]:
x=np.arange(4)
print("x = ",x)
print("add =",x+4)
print("div =",x/2)
print("floor div =",x//2)
print("modulo =",x%2)
print("power =",x**4)
print("negative =",-x)
print("negative =",np.negative(x))
print("absolute =",np.abs(x))
print("absolute =",np.absolute(x))

x =  [0 1 2 3]
add = [4 5 6 7]
div = [0.  0.5 1.  1.5]
floor div = [0 0 1 1]
modulo = [0 1 0 1]
power = [ 0  1 16 81]
negative = [ 0 -1 -2 -3]
negative = [ 0 -1 -2 -3]
absolute = [0 1 2 3]
absolute = [0 1 2 3]
